### ISSUE TITLE
vim --servername

### ISSUE THREAD

**Issue by dbeniamine** [brandonwillard/vim-setup#1]
Hi,

I found your repo by looking for synctex command for qpdfview, after a few errors I found out that the command: `vim --servername=VIM --remote +%2 %1` should be `vim --servername VIM --remote +%2 %1`. If the servername is actually  `VIM` it does not make any difference because by default `--remote` looks for a server named `VIM` but for mine who's name is `VIMTEX` it was not working.

Bye,
David

**Comment by brandonwillard** [comment]
Thanks for the heads-up!  I've actually moved to [neovim](https://neovim.io/) now--to satisfy my terminal needs--and I'm trying to find the time to set up a more elegant solution, like the one used in the [Nvim-R](https://github.com/jalvesaq/Nvim-R) plugin ([backward sync](https://github.com/jalvesaq/Nvim-R/blob/master/R/synctex_evince_backward.py) and [forward sync](https://github.com/jalvesaq/Nvim-R/blob/master/R/synctex_evince_forward.py)).  That said, I haven't touched/fixed/been able to use synctex recently. 
Anyway, the Vim server approach didn't seem like it could handle multiple Vim instances with different pdf viewers and files being synced, and I think the whole `dbus` + Nvim RPC approach is one broad solution that could cover `qpdfview`.

**Comment by dbeniamine** [comment]
Hi,

I've tryed neovim but didn't manage to make my config work in a reasonable time, maybe I'll try again an other time.

Concerning the need for terminal I use vim + [tmux](https://tmux.github.io/) and [vim-dispatch](https://github.com/tpope/vim-dispatch), and for the multi instance issue I have a bash alias that set the servername of my vim. It assumes that when I'm TeXing I start vim on my tex file and that I only tex with one vim at a time, there is the code just in case:

```
#Avoid nested session
if [ ! -z $(which tmux) ] && [ -z $TMUX ]
then

    function tvim()
    {
        # Using directly $@ seems to add a ' at the end of the first argument
        # which makes tmux bug so there is an ugly hack to recreate a clean
        # argument list
        arg=""
        while [ ! -z $1 ]
        do
            arg="$arg $1"
            shift
        done
        if [ ! -z "$DISPLAY" ] && [ -z "$(echo $arg | grep 'servername')" ]
        then
            # Need a server name
            if [ ! -z "$(echo $arg | grep '.tex')" ] \
            && [ -z "$(\vim --serverlist | grep 'VIMTEX')" ]
            then
                id="TEX"
            else
                id=$(\vim --serverlist | grep 'VIM[0-9][0-9]*' | wc -l)
            fi
            myopts="--servername VIM$id"
        fi
        tmux new-session "TERM=$TERM \vim $myopts $arg"
    }
    alias vim='tvim'
fi
alias vi='vim'
```

With that configuration synctex work pretty well in both sides, in qpdfview I have: `/usr/bin/vim --servername VIMTEX --remote +%2 %1`
